README.md
src/Projection/AbstractPDOProjection.php
src/Projection/AbstractPDOReadModelProjection.php
tests/Projection/MySQLEventStoreProjectionTest.php
tests/Projection/MySQLEventStoreQueryTest.php
tests/Projection/MySQLEventStoreReadModelProjectionTest.php
tests/Projection/PostgresEventStoreProjectionTest.php
tests/Projection/PostgresEventStoreQueryTest.php
tests/Projection/PostgresEventStoreReadModelProjectionTest.php

see: https://github.com/prooph/pdo-event-store/issues/10

add tests for stopping projections and queries, fix small bug

---

composer.json
src/Container/AbstractEventStoreFactory.php

The interesting thing is, we must not update `AbstractEventStoreFactory.php`. `dimensions(): array` is still valid, but for the consistency.

update to interop-config 2.0.0

---

src/MySQLEventStore.php
src/PostgresEventStore.php
src/Projection/ProjectionOptions.php
tests/AbstractPDOEventStoreTest.php
tests/Projection/MySQLEventStoreProjectionTest.php
tests/Projection/MySQLEventStoreQueryTest.php
tests/Projection/MySQLEventStoreReadModelProjectionTest.php
tests/Projection/PostgresEventStoreProjectionTest.php
tests/Projection/PostgresEventStoreQueryTest.php
tests/Projection/PostgresEventStoreReadModelProjectionTest.php
tests/Projection/ProjectionOptionsTest.php

resolves: prooph/event-store#226
depends on https://github.com/prooph/event-store/pull/228
when the change on event-store is accepted and merged, please restart this travis build again and it should turn green.

Add convenience methods to event store

---

src/Container/AbstractEventStoreFactory.php
src/Container/MySQLEventStoreFactory.php
src/Container/PostgresEventStoreFactory.php
tests/Container/MySQLEventStoreFactoryTest.php
tests/Container/PostgresEventStoreFactoryTest.php

This pr provides some expansions for the abstract event store factory to inject plugins and metadata enrichers from config. Currently this configurations would be ignored.

Factory improvements

---

src/PersistenceStrategy/PostgresAggregateStreamStrategy.php
src/PersistenceStrategy/PostgresSimpleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php

Fixes #27: Since the payload column simply stores JSON data it is more efficient to use the JSON datatype of PostgreSQL as no conversion happens when the data is getting stored or read.

Convert PostgreSQL payload column from JSONB to JSON.

---

phpunit.xml.pdo_mysql
phpunit.xml.pdo_pgsql
tests/Container/MySqlEventStoreFactoryTest.php
tests/Container/PostgresEventStoreFactoryTest.php

UnitTests would fail with messages like
> "Extension "pdo_pgsql" is not loaded"

adds missing phpunit group annotations to container test classes

---

src/PersistenceStrategy/MySqlSingleStreamStrategy.php

Using JSON_UNQUOTE to get rid of quotation marks in database values.

MySQL Database Scheme improvements

---

README.md

Since we are using JSON_EXTRACT shorthands like here:
https://github.com/prooph/pdo-event-store/blob/0dc302252b3fbde292cb68fafdd1579e1907fabf/src/MySqlEventStore.php#L285
MySQL Server Version >= 5.7.9 is required.
See https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-column-path
> In MySQL 5.7.9 and later, the -> operator serves as an alias for the JSON_EXTRACT() function when used with two arguments, a column identifier on the left and a JSON path on the right that is evaluated against the JSON document (the column value). You can use such expressions in place of column identifiers wherever they occur in SQL statements.

updates minimum MySQL server version to 5.7.9 in README

---

src/MySqlEventStore.php
src/PostgresEventStore.php

This PR provides changes on queries for hasStream requests on MySQL and Postgres.
On MySQL, this query could be done only with index file and without fetching real data from db-table.
Since the `stream_name` is not relevant there is no need to fetch it, which results in a performance improvement.
Not sure about Postgres, but should be the same how on MySQL.
Note that fetchColumn for MySQL would return a string, but an integer on Postgres.

SQL Query improvements

---

scripts/mysql/01_event_streams_table.sql
scripts/mysql/02_projections_table.sql
scripts/postgres/01_event_streams_table.sql
scripts/postgres/02_projections_table.sql
src/MySqlEventStore.php
src/PdoStreamIterator.php
src/PersistenceStrategy/MySqlAggregateStreamStrategy.php
src/PersistenceStrategy/MySqlSimpleStreamStrategy.php
src/PersistenceStrategy/MySqlSingleStreamStrategy.php
src/PersistenceStrategy/PostgresAggregateStreamStrategy.php
src/PersistenceStrategy/PostgresSimpleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php
src/PostgresEventStore.php

Currently the queries in aggregate load methods from event stores builds queries and recreate this for batch requests.
This PR changes this behavior and implements prepared statements. The PdoStreamIterator has only to change the values for `fromNumber` and `limit` without have to know how to queries should be builded.

use prepared load statements

---

src/Projection/PdoEventStoreReadModelProjection.php

escaping so FQCN can by used a name

name should be escaped

---

src/MySqlEventStore.php

when $metadataMatcher = null thing went boom

Fetch method load fix

---

src/HasQueryHint.php
src/MySqlEventStore.php
src/PersistenceStrategy/MySqlAggregateStreamStrategy.php
src/PersistenceStrategy/MySqlSimpleStreamStrategy.php
src/PersistenceStrategy/MySqlSingleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php
tests/Container/MySqlProjectionManagerFactoryTest.php
tests/MySqlEventStoreTest.php

resolves https://github.com/prooph/pdo-event-store/issues/43
/cc @basz @oqq

Improve event store indexes

---

src/Exception/ProjectionNotCreatedException.php
src/Projection/PdoEventStoreProjector.php
tests/Projection/PdoEventStoreProjectorTest.php

This is an attempt to fix #76 
Unfortunately configuring the PDO connection from the beginning to throw exceptions on errors will result in almost all tests failing.
I think this should be addressed, but I believe it's outside of the scope of current issue.
@prolic any suggestions on how to make this better ?

Catch and ignore duplicate projection error when creating it

---

composer.json
src/MySqlEventStore.php
src/PostgresEventStore.php
tests/AbstractPdoEventStoreTest.php

see https://github.com/prooph/event-store/pull/286
see https://github.com/prooph/event-store/issues/284

Support message property filters + new operators

---

docker-compose-tests.yml

Each container will have it's own IP that you can use to connect to MySQL/Postgres.
This commit allows for people running existing applications on these ports not to have to stop them as there is no reason to bind in the first place.
The `composer` container will have access to the other containers regardless.

Remove port bindings from docker-compose

---

composer.json
docker-compose-tests.yml

Unable to run the tests due to file names not matching in composer.json to the actual file names.

Fix path to phpunit files from composer.json

---

README.md

I think it may be favourable to have the Docker way work without configuration example environment flags for the sacrifice using composer on host machine.
The way around this is we could revert what I did previously and use a `docker_tests.sh` which will set the correct environment variable, wait for the database to be available and execute the test.

Documentation update for running tests.

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

/cc @fritz-gerneth can you test if this works for you?

update lock after sleep

---

composer.json
src/Projection/MariaDbProjectionManager.php
src/Projection/MySqlProjectionManager.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php
src/Projection/PostgresProjectionManager.php
tests/Projection/PdoEventStoreProjectorTest.php
tests/Projection/PdoEventStoreReadModelProjectorTest.php
tests/Projection/isolated-projection.php
tests/Projection/isolated-read-model-projection.php

Currently there is no way to gracefully shut down a running projection when any OS signals are received. Setting the projection is `stopping` state via a custom CLI script is not always an option (e.g. when projections and others are managed by supervisord). 
I think how the different signals should be handled should be left to the programmer, I have included a short example for reference below. In any case, to support this feature the projection loop at least needs to trigger the signal dispatch function.
Some remarks on my approach:
- `declare(ticks=1)` is not required anymore to my knowledge, it got replaced by `pcntl_signal_dispatch`
- I made this argument optional, defaulting to `false` to remain fully backwards compatible
- The location of the `triggerPcntlSignalDispatch` call …

Optionally trigger pcntl_signal_dispatch

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

resolves https://github.com/prooph/pdo-event-store/issues/98#issuecomment-314066675
The problem comes from
`$dateTime->modify('+200 ms');` is invalid, you can only add seconds, minutes, hours, and so on, but no micro- or milliseconds. This this needed to be worked around.

fix lock until string

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreQuery.php
src/Projection/PdoEventStoreReadModelProjector.php

resolves https://github.com/prooph/pdo-event-store/issues/97
/cc @simon-ondrej

optimize fromCategories event store queries

---

src/PostgresEventStore.php

`transactional()` should rollback on any \Throwable, not just exceptions.

Catch Throwable in transactional()

---

src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php
tests/MariaDbEventStoreTest.php
tests/MySqlEventStoreTest.php
tests/PostgresEventStoreTest.php

If an error occurs while creating a stream table, the stream table dropping produces a new error because the table doesn't exists. In this case `removeStreamFromStreamsTable` is not called and a corresponding record from the streams table is not deleted.

Drop stream table only if it exists

---

src/PostgresEventStore.php

This hotfix should be merged an released ASAP. Better fix will be later in https://github.com/prooph/pdo-event-store/pull/117.

Fix silently ignored errors in PostgresEventStore

---

src/MySqlEventStore.php

Unquoting extraction operator ->> was introduced in 5.7.13 and min. req. version (in README) is 5.7.9.
So either min. required version needs to get bumped to 5.7.13 or we use the JSON_UNQUOTE function.

Use JSON_UNQUOTE instead of unquoting operator

---

composer.json
src/Projection/MariaDbProjectionManager.php
src/Projection/MySqlProjectionManager.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php
src/Projection/PostgresProjectionManager.php
tests/Projection/PdoEventStoreProjectorTest.php
tests/Projection/PdoEventStoreReadModelProjectorTest.php
tests/Projection/isolated-projection.php
tests/Projection/isolated-read-model-projection.php
tests/TestUtil.php

This PR provides the implementation for the new projection option `update lock threshold`, see https://github.com/prooph/event-store/pull/331

Add projection option:  update lock threshold

---

src/Exception/ConcurrencyExceptionFactory.php
src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php

Closes #161.
I don't think we can easily detect if the problem was an aggregate ID or an event ID (not without an additional select to check for duplicates). However the information seems to be in PDO's ErrorInfo so I'd like to simply pass it along in the exception message.
This will of course require another PR for `ActionEventEmitterEventStore` to pass the message along [here](https://github.com/prooph/event-store/blob/master/src/ActionEventEmitterEventStore.php#L88-L89) instead of the boolean.
I'll send that PR later. Unless of course you're against this solution.

Add message to ConcurrencyException

---

docs/variants.md

Typo that causes the link to not render as a link.

Double bracket typo

---

.travis.install-mariadb-10.2.14.sh
.travis.yml
src/MariaDbEventStore.php

Prior to MariaDB 10.2.16, json_value would return the `true` or `false`
string when fetching a boolean json data. From 10.2.16, it returns the
`1` or `0` integer.
See https://jira.mariadb.org/browse/MDEV-15905
See https://github.com/prooph/pdo-event-store/issues/164
The solution provided here is to use `json_extract` which behavior hasn't changed (it always return `0` or `1` when fetching boolean json data).
--
Side Note: The testsuite passes with MariaDB 10.3.9 (locally), I could work on adding it to the travis build if that's something you'd be interested in @prolic @codeliner ?

Removed usage of mariadb json_value with boolean

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreQuery.php
src/Projection/PdoEventStoreReadModelProjector.php

Implementation a second optional parameter for fromStream Methods. So its possible to filter Streams for Projections, Queries and so on. As example is it possible to filter for an AggregationID to create Projections for a single Aggregate with the SingleStream- or SimpleStreamStrategy
- related to: https://github.com/prooph/event-store/pull/350

Implement a second optional MetadataMatcher parameter for fromStream methods

---

src/PostgresEventStore.php

Fix reference error in PostgresEventStore for MetadataMatcher with IN Operations.
The removed value reference leads to wrong values for the IN operation.
Example:
```
(new MetadataMatcher())
->withMetadataMatch(
'event_name',
Operator::IN(),
[
'Event-1',
'Event-2'
],
FieldType::MESSAGE_PROPERTY()
)
```
Results to:
```
$values = [
'metadata_0_0' => 'Event-1',
'metadata_0_1' => 'Event-1'
]
```
The Second values is replaced by the value reference with the first one.

Fix reference error in PostgresEventStore for MetadataMatcher with IN Operations

---

src/Projection/PdoEventStoreProjector.php

closes #198
Since PHP 7.1 it's possible to manipulate DateTime instances microseconds, so
I was able to drop the old mechanism that did that manually

Fixes projection lock string generation

---

composer.json
src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php

superseeds https://github.com/prooph/pdo-event-store/pull/207
/cc @basz @fritz-gerneth @codeliner @unhappyby
The tests still pass, so this should work without making any BC. Please let me know what you think.

don't execute count statement on load

---

src/PersistenceStrategy/PostgresAggregateStreamStrategy.php
src/PersistenceStrategy/PostgresSimpleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php

Currently when a tableName with a dot is presented the name can correctly
be split up into schema and table name. But when the schema does not
exist the whole proces breaks as the table can not be created in a
non-existing space.
This commit adds an SQL-statement to the createSchema-function that – in
case a schema was given – will create the schema when it does not yet
exist.

Add Schema-Creation to createSchema function

---

src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php
tests/MariaDbEventStoreTest.php
tests/MySqlEventStoreTest.php
tests/PostgresEventStoreTest.php

This PR prevents a BC break introduced in https://github.com/prooph/pdo-event-store/pull/217 by reverting the event stores constructor signature.
It also triggers a deprecation error to prepare users to future BC break (in 2.0.0).

Restores custom strategy backward compatibility

---

docs/variants.md
src/Projection/GapDetection.php
src/Projection/MariaDbProjectionManager.php
src/Projection/MySqlProjectionManager.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php
src/Projection/PostgresProjectionManager.php
tests/Projection/MariaDbEventStoreProjectorTest.php
tests/Projection/MariaDbEventStoreReadModelProjectorTest.php
tests/Projection/MySqlEventStoreProjectorTest.php
tests/Projection/MySqlEventStoreReadModelProjectorTest.php
tests/Projection/PdoEventStoreProjectorTest.php
tests/Projection/PdoEventStoreReadModelProjectorTest.php
tests/Projection/PostgresEventStoreProjectorTest.php
tests/Projection/PostgresEventStoreReadModelProjectorTest.php
tests/TestUtil.php

Fixes https://github.com/prooph/pdo-event-store/issues/189
The PR adds a "gap detection" mechanism to projections. This means, that if the projection detects a gap in the stream position while processing events, it pauses processing for a configurable time, before rereading events from the last known position. 
Gap detection is disabled by default.
```php
$gapDetection = new GapDetection();
$projection = $projectionManager->createProjection('test_projection', [
PdoEventStoreProjector::OPTION_GAP_DETECTION => $gapDetection,
]);
``` 
```php
$gapDetection = new GapDetection(
// Configure retries in case a gap is detected
[
0, // First retry without any sleep time
10, // Second retry after 10 ms
30, // Wait another 30 ms before performing a third retry
],
\DateInterval('PT60S') //Set …
```

Add gap detection to projections

---

docker-compose-tests.yml

The current version of the PostgreSQL docker container requires a non-empty password to be set. The docker-compose log shows the following error:
> Error: Database is uninitialized and superuser password is not specified.
> postgres_1  |        You must specify POSTGRES_PASSWORD to a non-empty value for the
> postgres_1  |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
> postgres_1  |
> postgres_1  |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
> postgres_1  |        connections without a password. This is *not* recommended.
Despite the warning at the end, it is certainly appropriate to trust all connections for the test database.

Fix docker compose setup for PostgreSQL

---

src/MySqlEventStore.php

The return of the pdo statement when executing `$statement->fetchColumn()` in php8.1 is an integer. So the `'1' === $statement->fetchColumn();` will fail. 
Since we check if we got 1 or 0, which is always a number, casting to int makes it a more secure check.

Fix MysqlEventStore checking if stream exists for php8.1

---

src/WriteLockStrategy/MysqlMetadataLockStrategy.php
tests/WriteLockStrategy/MysqlMetadataLockStrategyTest.php

After updating our application to PHP 8.1 and updating our dependencies, all functions that tried to save our event store models failed because of a failure to get a lock. It seems like either the PHP update or an update of a doctrine library changed the return value of the GET_LOCK MySQL function to return int instead of a string.

Allow int return values from GET_LOCK MySQL function

---

src/MariaDbEventStore.php

Compare operation fails when `$statement->fetchColumn()` returns a numeric value
fix #240

fix(mariadb): hasStream failed to detect existing stream

---

src/Projection/MariaDbProjectionManager.php
src/Projection/MySqlProjectionManager.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php
src/Projection/PostgresProjectionManager.php

with large amount of events to load being able to load only part of it improves performance on reloading projection

enable to set amount of event being loaded in single run

---

src/Projection/PdoEventStoreReadModelProjector.php
tests/Projection/AbstractPdoEventStoreReadModelProjectorTestCase.php

projections should keep running when:
- runs with `keepRunning: true` due it awaits for new events
- it did not reached end of the stream, e.g. in case of resetting
projection status should indicate actual status of projection therefore, `idle` should be set if projection wasn't supposed to keep running or end of stream was reached

keep projections running as long events are loading
