.travis.yml
composer.json

Improves travis and composer config by only fetch prooph components by source, instead of all packages

Travis config improvement

---

src/Projection/PdoEventStoreReadModelProjection.php
tests/Projection/MySqlEventStoreReadModelProjectionTest.php
tests/Projection/PostgresEventStoreReadModelProjectionTest.php

Always call reset projection

---

src/MySqlEventStore.php
src/PostgresEventStore.php
src/Projection/PdoEventStoreProjection.php
src/Projection/PdoEventStoreQuery.php
src/Projection/PdoEventStoreReadModelProjection.php
tests/AbstractPdoEventStoreTest.php
tests/MySqlEventStoreTest.php
tests/PostgresEventStoreTest.php
tests/Projection/PdoEventStoreProjectionTestCase.php

resolves https://github.com/prooph/event-store/issues/252
based on https://github.com/prooph/event-store/pull/253
Restart the travis build, after https://github.com/prooph/event-store/pull/253 is merged.

change EventStore::load method

---

src/Projection/PdoEventStoreProjection.php
src/Projection/PdoEventStoreReadModelProjection.php

fixes https://github.com/prooph/pdo-event-store/issues/57
/cc @oqq

PersistBlockSize projection option works not properly

---

src/Container/AbstractEventStoreFactory.php
src/Container/MySqlEventStoreFactory.php
src/Container/PdoConnectionFactory.php
src/Container/PostgresEventStoreFactory.php
tests/Container/MySqlEventStoreFactoryTest.php
tests/Container/PdoConnectionFactoryTest.php
tests/Container/PostgresEventStoreFactoryTest.php

Add PDO connection factory

---

phpunit.xml.pdo_mysql
phpunit.xml.pdo_pgsql
src/Container/AbstractEventStoreFactory.php
src/Container/AbstractProjectionManagerFactory.php
src/Container/MySqlProjectionManagerFactory.php
src/Container/PostgresProjectionManagerFactory.php
tests/Container/MySqlProjectionManagerFactoryTest.php
tests/Container/PostgresProjectionManagerFactoryTest.php

resolves https://github.com/prooph/pdo-event-store/issues/60
no tests yet

Projection manager factory

---

src/MySqlEventStore.php
src/PdoStreamIterator.php
src/PostgresEventStore.php

resolves https://github.com/prooph/event-store/issues/271
/cc @oqq

Remove PHP_INT_MAX constant from interface

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

depends on https://github.com/prooph/event-store/pull/280

remove lock timeout option (added to event-store interface)

---

composer.json
docs/bookdown.json
docs/interop_factories.md
docs/pdo_event_store.md
src/MySqlEventStore.php
src/PersistenceStrategy.php
src/PersistenceStrategy/MySqlAggregateStreamStrategy.php
src/PersistenceStrategy/MySqlSimpleStreamStrategy.php
src/PersistenceStrategy/MySqlSingleStreamStrategy.php
src/PersistenceStrategy/PostgresAggregateStreamStrategy.php
src/PersistenceStrategy/PostgresSimpleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php
src/PostgresEventStore.php

resolves https://github.com/prooph/pdo-event-store/issues/31
/cc @basz @oqq

remove uniqueViolationErrorCodes from persistance strategy + add docs

---

docs/pdo_event_store.md

resolves https://github.com/prooph/pdo-event-store/issues/73

improve docs

---

.travis.yml
phpunit.xml.pdo_mysql
phpunit.xml.pdo_pgsql
src/Exception/RuntimeException.php
src/MySqlEventStore.php
src/PdoStreamIterator.php
src/PostgresEventStore.php
src/Projection/MySqlProjectionManager.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreQuery.php
src/Projection/PdoEventStoreReadModelProjector.php
src/Projection/PostgresProjectionManager.php
tests/AbstractPdoEventStoreTest.php
tests/Projection/MySqlEventStoreProjectorTest.php
tests/Projection/MySqlEventStoreReadModelProjectorTest.php
tests/Projection/MySqlProjectionManagerTest.php
tests/Projection/PdoEventStoreProjectorTest.php
tests/Projection/PdoEventStoreQueryTest.php
tests/Projection/PdoEventStoreReadModelProjectorTest.php
tests/Projection/PostgresEventStoreProjectorTest.php
tests/Projection/PostgresEventStoreReadModelProjectorTest.php
tests/Projection/PostgresProjectionManagerTest.php
tests/TestUtil.php

PDOExceptions are now caught and pdo error codes are checked.
This follows the discussion from #77

Catch PDOExceptions and check error codes

---

src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PersistenceStrategy/MariaDbAggregateStreamStrategy.php
src/PersistenceStrategy/MariaDbSimpleStreamStrategy.php
src/PersistenceStrategy/MariaDbSingleStreamStrategy.php
src/PersistenceStrategy/MySqlAggregateStreamStrategy.php
src/PersistenceStrategy/MySqlSimpleStreamStrategy.php
src/PersistenceStrategy/MySqlSingleStreamStrategy.php
src/PersistenceStrategy/PostgresAggregateStreamStrategy.php
src/PersistenceStrategy/PostgresSimpleStreamStrategy.php
src/PersistenceStrategy/PostgresSingleStreamStrategy.php
src/PostgresEventStore.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php
tests/AbstractPdoEventStoreTest.php

resolves https://github.com/prooph/pdo-event-store/issues/87

Remove JSON_FORCE_OBJECT

---

docs/pdo_event_store.md
src/Container/AbstractEventStoreFactory.php
src/Container/MariaDbEventStoreFactory.php
src/Container/MySqlEventStoreFactory.php
src/Container/PostgresEventStoreFactory.php
src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php
tests/AbstractPdoEventStoreTest.php
tests/MariaDbEventStoreTest.php
tests/MySqlEventStoreTest.php
tests/PostgresEventStoreTest.php

resolves https://github.com/prooph/pdo-event-store/issues/102
related to https://github.com/prooph/event-store/issues/292
/cc @max-voloshin

Disable transaction handling

---

src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PdoStreamIterator.php
src/PostgresEventStore.php

resolves https://github.com/prooph/pdo-event-store/issues/103
/cc @sandrokeil

remove connection property from stream iterator

---

src/Exception/JsonException.php
src/PdoStreamIterator.php
tests/AbstractPdoEventStoreTest.php
tests/MySqlEventStoreTest.php

I am not sure about a unit test and if it is ok to use an own exception. Is this a correct style for prooph?

PdoStreamIterator should check json_last_error after json_decode

---

README.md
docs/introduction.md
src/MariaDbEventStore.php

resolves https://github.com/prooph/pdo-event-store/issues/116
@hvanoch can you verify this resolves it?
/cc @oqq @Adapik

bump mariadb requirements to 10.2.11

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

Always update the projections position

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

Calculate seconds and initialize interval with it

---

src/MariaDBIndexedPersistenceStrategy.php
src/MariaDbEventStore.php
src/PersistenceStrategy/MariaDbAggregateStreamStrategy.php
src/PersistenceStrategy/MariaDbSingleStreamStrategy.php
tests/Assets/PersistenceStrategy/CustomMariaDbAggregateStreamStrategy.php
tests/Assets/PersistenceStrategy/CustomMariaDbSingleStreamStrategy.php

MariaDB index mapping

---

src/PersistenceStrategy/MariaDbSingleStreamStrategy.php

Fix index metadata in MariaDb single stream strategy

---

src/PersistenceStrategy/MySqlAggregateStreamStrategy.php
src/PersistenceStrategy/MySqlSimpleStreamStrategy.php
src/PersistenceStrategy/MySqlSingleStreamStrategy.php
tests/Assets/PersistenceStrategy/CustomMySqlAggregateStreamStrategy.php
tests/Assets/PersistenceStrategy/CustomMySqlSimpleStreamStrategy.php
tests/Assets/PersistenceStrategy/CustomMySqlSingleStreamStrategy.php

As per #155
I've only changed MySQL.

Change MySQL tables to utf8mb4

---

src/PersistenceStrategy/MariaDbAggregateStreamStrategy.php
src/PersistenceStrategy/MariaDbSimpleStreamStrategy.php
src/PersistenceStrategy/MariaDbSingleStreamStrategy.php

Change MariaDB tables to utf8mb4

---

src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreReadModelProjector.php

Closes #160.
I can't really think of a good test for this since the end result is exactly the same except database logs. However I've tried some on purpose broken implementations and the tests failed every time so I think we're covered.

Check if projection exists before creating it

---

docs/variants.md

Reported here: https://stackoverflow.com/a/51310542/6748089

Fix create_event_stream example links

---

src/Projection/PdoEventStoreProjector.php

Fixes https://github.com/prooph/pdo-event-store/issues/194

Removes position update from lock update

---

src/Projection/PdoEventStoreReadModelProjector.php

this will let client know that projection may need to be run once more if events are loaded in limited batch

set to IDLE when no events loaded

---

src/MariaDbEventStore.php
src/MySqlEventStore.php
src/PostgresEventStore.php
src/Projection/GapDetection.php
src/Projection/PdoEventStoreProjector.php
src/Projection/PdoEventStoreQuery.php
src/Projection/PdoEventStoreReadModelProjector.php
tests/Projection/PdoEventStoreProjectorTest.php
tests/Projection/PdoEventStoreReadModelProjectorTest.php

Follow-up of https://github.com/prooph/event-store/pull/435

remove php8.4 deprecation warnings

---

.github/workflows/integration.yaml
src/Projection/PdoEventStoreReadModelProjector.php

compatibility with https://github.com/prooph/event-store/pull/442
